
#set up properties
PROJECT_ID: spring-security-jwt-351909

server:
    port: 8080

spring:
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, firestore
            label: master
        gcp:
            credentials:
                location: classpath:key.json  
            firestore:
                project-id: ${PROJECT_ID:spring-security-jwt-351909}
                enabled: true

settings:
    cors_origin: '*'